# Generated by Django 4.0.4 on 2023-08-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.TextField(max_length=255)),
                ('lastName', models.TextField(max_length=255)),
            ],
        ),
    ]
